---

- name: Setup environment variables
  copy: dest=/etc/environment content="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games\nPYTHONPATH=/home/mangrover/workspace/datawinners/\n"

- name: Create group
  group: name={{user}} state=present

- name: Create user
  user: name={{user}} createhome=yes group={{user}} shell=/bin/bash state=present

- name: Set file limits for user {{user}}
  lineinfile: dest=/etc/security/limits.conf line="{{item}}" regexp="{{item}}" insertafter=EOF backup=yes
  with_items:
    - "{{user}} soft nofile 65000"
    - "{{user}} hard nofile 65000"

- name: Install python dependencies
  apt: name={{item}} state=latest
  with_items:
    - python-pip
    - python-dev
    - build-essential
    - python-gdal

- name: install and update pip modules
  pip: name={{item}} state=latest
  with_items:
    - pip
    - virtualenv

- name: Create virtual environment folder
  file: path=/home/{{user}}/virtual_env state=directory owner={{user}} group={{user}}

- name: Create virtual environment
  file: path=/home/{{user}}/virtual_env/datawinners state=directory owner={{user}} group={{user}}

- name: Install pip into virtual environment
  pip: name=pip virtualenv=/home/{{user}}/virtual_env/datawinners state=latest

- name: Create DataWinners log folder
  file: path="/var/log/datawinners" state=directory owner={{user}} group={{user}}

- name: Create DataWinners workspace
  file: path=/home/{{user}}/workspace state=directory

- name: Checkout DataWinners git repostiory
  git: repo=https://github.com/mangroveorg/datawinners.git dest=/home/{{user}}/workspace/datawinners

- name: Checkout Shape files git repostiory
  git: repo=https://github.com/mangroveorg/shape_files.git dest=/home/{{user}}/workspace/shape_files

- name: Checkout custom reports git repostiory
  git: repo=https://github.com/mangroveorg/custom_reports.git dest=/home/{{user}}/workspace/custom_reports

- name: Set DataWinners workspace ownership
  file: path="/home/{{user}}/workspace" state=directory owner={{user}} group={{user}} recurse=yes

- name: Install DataWinners pip requirements
  pip: requirements=/home/{{user}}/workspace/datawinners/datawinners/requirements.pip virtualenv=/home/{{user}}/virtual_env/datawinners

- name: Install uwsgi
  include: uwsgi.yml

- name: Install apt dependencies
  apt: name={{item}} state=latest
  with_items:
    - libxslt1-dev
    - libxml2-dev

- name: Install memcached
  include: memcached.yml

- name: Set pam.d common-session
  template: src=etc/pam.d/common-session.j2 dest=/etc/pam.d/common-session

- name: Set pam.d common-session-noninteractive
  template: src=etc/pam.d/common-session.j2 dest=/etc/pam.d/common-session-noninteractive

- name: Install rabbitmq
  include: rabbitmq.yml
