---

- name: Setup environment variables
  copy: dest=/etc/environment content="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games\nPYTHONPATH=/home/mangrover/workspace/datawinners/\n"

- name: Create group
  group: name={{user}} state=present

- name: Create user
  user: name={{user}} createhome=yes group={{user}} shell=/bin/bash state=present

- name: Install python dependencies
  apt: name={{item}} state=latest
  with_items:
    - python-pip
    - python-dev
    - build-essential
    - python-gdal

- name: install and update pip modules
  pip: name={{item}} state=latest
  with_items:
    - pip
    - virtualenv

- name: Create virtual environment folder
  file: path=/home/{{user}}/virtual_env state=directory owner={{user}} group={{user}}

- name: Create virtual environment
  file: path=/home/{{user}}/virtual_env/datawinners state=directory owner={{user}} group={{user}}

- name: Install pip into virtual environment
  pip: name=pip virtualenv=/home/{{user}}/virtual_env/datawinners state=latest

- name: Create DataWinners log folder
  file: path="/var/log/datawinners" state=directory owner={{user}} group={{user}}

- name: Install uwsgi
  include: uwsgi.yml

- name: Create DataWinners workspace
  file: path=/home/{{user}}/workspace state=directory owner={{user}} group={{user}}

- name: Checkout DataWinners git repostiory
  git: repo=https://github.com/mangroveorg/datawinners.git dest=/home/{{user}}/workspace

- name: Checkout Shape files git repostiory
  git: repo=https://github.com/mangroveorg/shape_files.git dest=/home/{{user}}/workspace

- name: Checkout custom reports git repostiory
  git: repo=https://github.com/mangroveorg/custom_reports.git dest=/home/{{user}}/workspace

- name: Set DataWinners workspace ownership
  file: path="/home/{{user}}/workspace" state=directory owner={{user}} group={{user}} recurse=yes










