---
- name: Setup dev box
  hosts: 127.0.0.1
  roles:
    - { role: web-server, user: "{{ansible_ssh_user}}" }
    - { role: db-server, user: "{{ansible_ssh_user}}" }
#    - db-server
#    - search-server