---

- name: Create CouchDB group
  group: name=couchdb state=present

- name: Create CouchDB user
  user: name=couchdb createhome=no home=/opt/apache-couchdb system=yes group={{user}} shell=/bin/sh state=present

- name: Install CouchDB apt packages
  apt: name={{item}} state=present
  with_items:
    - wget
    - libicu-dev
    - libmozjs185-dev
    - libcurl4-gnutls-dev
    - libtool
    - erlang-base-hipe
    - erlang-eunit
    - erlang-nox
    - erlang-xmerl
    - erlang-inets

- name: Check if CouchDB package has already been downloaded
  stat: path=/opt/{{couchdb_package_name}}
  register: couchDB_package

- name: Download CouchDB package
  get_url: url="{{couchdb_deb_url}}" dest=/opt/
  when: not couchDB_package.stat.exists

- name: Install CouchDB
  apt: deb=/opt/{{couchdb_package_name}} state=installed

- name: Create CouchDB directories
  file: path={{item}} state=directory
  with_items:
    - /opt/apache-couchdb/var/log/couchdb
    - /opt/apache-couchdb/var/run/couchdb
    - /opt/apache-couchdb/var/lib

- name: Set owner and group for CouchDB folders
  file: path=/opt/apache-couchdb owner=couchdb group=couchdb state=directory

