
- name: ensure packages are installed
  action: apt name={{ item }}
  with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2

- name: Allow password authentication or local socket user
  sudo: yes
  copy: src=../templates/postgresdb/default/pga_hba.conf
        dest=/etc/postgresql/9.1/main/pga_hba.conf
        force=yes
  notify: Restart Postgres

- name: Create Database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ postgresDB_name }}

- name: Create User
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ postgresDB_user_name }} password={{ postgresDB_password }} state=present role_attr_flags=NOSUPERUSER,CREATEDB

- name: Provide user with DB permissions
  sudo: yes
  sudo_user: postgres
  postgresql_user: user={{ postgresDB_user_name }} db={{ postgresDB_name }} priv=ALL


- name: Restart Postgres
  service: name=postgresql state=restarted
