
- name: ensure packages are installed
  action: apt name={{ item }}
  with_items:
      - postgresql-server-dev-9.1
      - postgresql-9.1-postgis
      - python-psycopg2

- name: Allow password authentication on local socket user
  template: src=postgresdb/default/pga_hba.conf.j2 dest=/etc/postgresql/9.1/main/pga_hba.conf

- name: Create User
  sudo_user: postgres
  postgresql_user: name={{ postgres_user_name }} state=present role_attr_flags=SUPERUSER,CREATEDB

- name: Create Database
  sudo_user: postgres
  postgresql_db: name=mangrove owner={{ postgres_user_name }} encoding='UTF-8'


- name: Provide user with DB permissions
  sudo_user: postgres
  postgresql_user: user={{ postgres_user_name }} db=mangrove priv=ALL

- name: Start Postgres
  service: name=postgresql state=started
